# Default values for a nodejs14nginx117 app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: artifacts.bcp.absa.co.za/alt-phys-chan-team-docker-local/atm-marketing_apc-portal
  tag: latest
  pullPolicy: IfNotPresent

buildID: test

service:
  type: ClusterIP
  externalPort: 80
  internalPort: 8080
  annotations:
    fabric8.io/expose: "true"
    fabric8.io/ingress.annotations: "kubernetes.io/ingress.class: nginx"

subatomic:
  sub-team: alt-phys-chan-team
  sub-project: atm-marketing
  sub-application: apc-portal

env:
  TZ: "Africa/Johannesburg"

ingress:
  tls: true

resources:
  requests:
    memory: "100Mi"
    cpu: "250m"
  limits:
    memory: "500Mi"
    cpu: "1"
